### ISSUE TITLE
Agenda and programming inspirations

### ISSUE THREAD

**Issue by benhylau** [dweb-camp-2019/organizing#52]
Collection of research into strategies for agenda and program co-creation.

**Comment by benhylau** [comment]
Thoughts on Enspiral Retreat article
---
I want to share this [article by Richard D. Bartlett](http://richdecibels.com/stories/congregation-how-to/congregation-how-to.html) about the 2019 Enspiral Retreat:

Although it is for a smaller retreat for 65 people, it has a lot of strategies we can employ as camp organizers: 

- Co-created agenda:
	- Everyone is a co-creator, this is _our_ gathering not the organizer's or anyone else's
	- Organizer role is to curate the culture by inviting the people we feel carry this culture we want, not to curate the talks
	- Although Chaos Congress has speakers, it definitely feels like _our_ conference as some people go only to the Assemblies and set up Villages, the "talks" is part of the event not _the_ event (we can also have curated speakers but just as a small component)
	- Everyone is a producer and consumer
- Retreat crews:
	- This forces a small trust group for people to go to
	- Shares similarity to "you can't set up your tent within 100 feet of someone you know" rule
- 70/30 ratio:
	- The 30 being new people in the Enspiral Retreat
	- I think this can also apply to having the 70 being people who would set the culture

**Comment by benhylau** [comment]
Agenda from RadicalxChange
---

![D2Yv6A-WsAIuj6j](https://user-images.githubusercontent.com/2261308/55042690-0fb5a100-5009-11e9-9593-e2c5552543e2.jpg)

**Comment by okdistribute** [comment]
Might also want to check out how SSB 'scuttle camp' was done -- people seemed to really like that. cc @noffle @dariusk

**Comment by benhylau** [comment]
@karissa Yes! We have arranged to meet up with @noffle to sync up on scuttlecamp this weekend :)

**Comment by mixmix** [comment]
> 70/30 ratio

I think you got it round the wrong way. I think you can run on a minimum of 30-40 % who carry the culture. In the case of this community I don't know if you have 150-200 people with enough of a shared culture that that makes sense here though do you? This is a more ephemeral community (unless I'm wrong)

If you don't have this 30-40% then I think you need to either very explicitly introduce a culture, and spell it out quite a lot, or make a bunch of space for the group to form a culture together. ... but this all depends on the type of event you're going for. I think if it's a "co-created" / "shared ownership" type thing, which I sense it is, then this applies

**Comment by benhylau** [comment]
@mixmix reading this, I felt the the 70% refers to people who are returning:

>This year about 30% of the retreat participants were newcomers. With this 70-30 ratio, most people already know "how we do things around here", their existing relationships and past experiences provide orientation. In previous events we've pushed this ratio to 50-50, and it was much harder to create a sense of coherence, intimacy, and safety.

In terms of explicitly introducing a culture, yes we definitely want to be upfront about how people should treat each other. This culture is not only determined by Internet Archive / DWeb, but also of the people at the Farm. After meeting them the past weekend I feel we definitely share a lot of that!

In terms of what types of conversations will happen, as organizers we have discussed our individual visions for Camp 2019 and our more distant future. We have established that shared understanding, and that has been informing the branding work Iryna is doing.

While being mindful this is a 500 people event with broad scopes, we do want to "curate the audience" by making efforts to invite and support specific people to come, so we are less biased towards the traditional audiences that would show up at such an event, and to make spaces so they are empowered to share their message.

The projects, conversations, programming we'd like to be co-created with shared ownerships. So we are thinking on ways to help facilitate the _pre-event process_ of connecting and co-creating (is it on [a GitHub Issues page](https://github.com/dweb-camp-2019/applications) that people can connect and evolve a project idea?) and _at-event tools_ so people can discover gatherings at 500 people event spanning large geographical areas :)

Yes, this is an ephemeral community, but I also see DWeb as a connecting space to build more permanence and continuity, where every instance is an opportunity to build more decentralized organizing capacity (I am thinking the various autonomous groups that attend and provide infra at CCC year after year) and to reflect on diversity and inclusion policies and "do better" for each next instance.

**Comment by mixmix** [comment]
> The projects, conversations, programming we'd like to be co-created with shared ownerships.

I like this goal. It's also another challenge accessibility wise. Notice that Github issues is on a platform some people know nothing about, and don't know how to use - already coders are advantaged here. Also, the people with abundant resources are able to _afford_ to contribute to volunteer pre-event coordinating. If you really want the input pre-event from a diverse crew, then I think the best bet might be offering to pay people for their time, so they can afford to access this.

That might not be feasible, but it's something to consider when we talk about _co-created_.

**Comment by benhylau** [comment]
Just to be clear, the current discussions on GitHub isn't the proposal process, that will be published mid-April on the website. The proposal process should definitely not _require_ GitHub. What we did for Our Networks 2018 was a GitHub Issues template _or_ by email, then organizers move the email content [into an Issue](https://github.com/ournetworks/2018-submissions/issues).

For DWeb, I am thinking:

1. GitHub Issues or PR template with fallback to email
2. GitHub Issues or PR template with fallback to Google Form
3. Posting on a wiki or self-host [frab](https://github.com/dweb-camp-2019/organizing/issues/7#issuecomment-472548594)

I am also hoping people can connect before making a project proposal, and so far this is happening on [GitHub Issues or real-time chat on bridged Matrix-IRC-Slack](https://github.com/dweb-camp-2019/organizing#get-involved). Obviously all these platforms are biased towards certain audiences. I would like to learn more about other ways to help people to connect. We are also reaching out through "offline" channels to audiences who wouldn't be on these platforms in the first place, but just proxying notes conversations onto GitHub.

**Comment by whanamura** [comment]
Here are some of the references we thought about when brainstorming:

**### What is our North Star?  Basic Principles & Legacy We’ll Leave Behind**
Goal: Let’s discuss the goals for the DWeb Camp.  Can we set out some first principles and ground rules that can guide us?  Then let’s turn our attention to what we want to leave behind--the outcomes and outputs we’ll share with others.

Here are some pillars from others for inspiration:
**1  The Farm Pillars:**

a.     treat everyone like family
b.     greet everyone with a hug
c.      nourishment—taking care of ourselves
d.     balance--finding a balance in life
f.      play is central
g.     Earth equals home & connection

**2.  The Farm Team Agreements**
Don’t take anything personally
Do your best
Be impeccable with your words
Don’t make assumptions
Mastery over mediocrity
Commitment to completion

**3.  BURNING MAN 10 PILLARS:**
Leave no trace
Radical participation
Radical inclusion
Civic responsibility-- it’s everyone’s responsibility to take care of each other
Immediacy (Do it!)
Radical gifting
De-commodification
Radical Self-reliance


**4.  Some Notes on First Principles for us:**
https://docs.google.com/document/d/1s4Ae88-TvlyQ42yfs4czQeLrlGIsuWPWW_BMxU_2VkY/edit?usp=sharing

**5.  DWEB SUMMIT Code of Conduct 2018**:  
https://decentralizedweb.net/conduct/


**6.  CAMP GROUNDED RULES:**
Skip don’t Run
No W talk 
Don’t ask anyone about age
Use nicknames not real names (reduces hierarchy)
Never turn your back to the Ocean.
Always leave the place better than how you found it.
Remember to look up…

**Comment by whanamura** [comment]
We went through a process to distill what we think is most important--First Principles or Pillars--for our camp:   (Please tell us what you think!)

**DWEB CAMP FIRST PRINCIPLES:**

_Co-created by a group of five organizers:  Pamela Pascual, Andi Wong, Benedict Lau, Ben Hanna, Wendy Hanamura, but open to more input!_

**TAKE CARE OF EACH OTHER**
We share a civic responsibility to care for each other, our camp, and the planet.  

So when you learn something new, bring someone else along. If someone needs assistance, pitch in and help!

Share what you have. Start from a place of abundance, in the belief that there will be enough for everyone.

Always leave a place better than when you found it
Leave no trace.  (That means carting out your creations as well as your trash when you leave, down to the micro level.)  Seek to generate zero waste through the creative reuse of materials

**JOY OF MISSING OUT (JOMO)**

There is more than you can ever possibly experience in one day at DWeb Camp. So we encourage you to be present and content with where you are at any given moment. 

Instead of comparing your experience to that of others, accept your experience at camp for what it is, not what you think it could have been. Be intentional with your time and that of others, but do not fret over time spent simply enjoying your stay. 

“Oh the joy of missing out. 
When the world begins to shout
And rush towards that shining thing;
The latest bit of mental bling–
Trying to have it, see it, do it,
You simply know you won't go through it;
The anxious clamoring and need
This restless hungry thing to feed.
Instead, you feel the loveliness;
The pleasure of your emptiness.
You spurn the treasure on the shelf
In favor of your peaceful self;
Without regret, without a doubt.
Oh the joy of missing out”
—Michael Leunig



**BE A BRIDGE.** 
Build bridges, not moats. The building of bridges enables radical connection - to yourself, to your community, to the environment and to the building of a better world.

Share goods, knowledge and experiences to span the unknown. Remember to leave space for others to join in. 

We like the metaphor of weaving. When you weave different materials together, you create a brand new whole. Weaving people together can be the first step to creating a culture of radical inclusion. 


**NOURISH MIND, BODY AND HEART**
Practice collective self-care to nourish your mind, body, and heart. 

Our creations take on the characteristics of their builders. Healthy technologies cannot be built by strained minds and stressful social relationships. Healthy resilient ecosystems flourish when the soil is well nourished.

So remember to look up at the sky.  Prioritize people over products. Greet each other as people not as a project or an opportunity.

**COME WITH A GROWTH MINDSET**
[                        ]  (intentionally blank)
We recognize that our shared futures require multiple, diverse imaginations and experiences. Be open to the unknown and create space for ideas you’ve yet to have, and for the ideas of others. Abandon preconceptions and allow events to change you. 

We are at a unique time in history to re-imagine and co-create a future based in our collective dream for a more just and sustainable world.  Don’t be afraid to ask questions and try new things. Dare to be naive, take risks and celebrate failure! There’s always more to learn.

**Comment by mixmix** [comment]
[EDIT] _echhh, if you reply from email all your formatting is killed_

**Comment by mixmix** [comment]
Really exciting seeing this come together. I think you've covered a bunch of really important topics

Couple of things that came up for me:
- **Some of the Burning Man principles are good, and some of them don't fit** . Specifically: Radical inclusion, Radical Self-reliance. I'm not up for including e.g. racists, this is paradox of tolerance territory. With Self-reliance, I think think this on runs against diversity/ inclusion/ accessibility.
- **Take care of each other** is a great goal. I believe it would be wise to put structures in place which support this, otherwise care falls to those who it systemically tends to fall on, and is not shared very evenly. The Support Crews / Faerie Rings we ran at scuttle-camp and enspiral fest are an example of a structure specifically designs to improve on the default.

**Comment by benhylau** [comment]
@mixmix we have flagged and discussed both those things in our planning, and I think they are excellent discussion topics for our call. I am hopping on a plane in a couple hours, and will try to summarize and publish as much of this material as I can before our Tuesday call.

@whanamura @mixmix thanks for publishing these in-progress notes and starting the discussion here.

**Comment by whanamura** [comment]
@mixmix Thank you for your thoughts both here and in the Google Doc.  https://docs.google.com/document/d/1wjr-nSdpi4f1E4Vg31N6HTDOR5r4qCD4pig-CirSllg/edit

We want to adopt the "Support Circles" structure and will be looking for perhaps as many as 40-50 leaders of these circles.  We'll also have a team of volunteers called "Links" who have an ongoing role "taking care of each other."

**Comment by whanamura** [comment]
**WELLNESS WORKSHOPS OFFERED BY THE FARM:**

One of the true benefits of The Farm where we will be staying is the rich community of people who live and work there. It's a hub of regenerative agriculture, renewable energy and live music.

Here are some of the workshops/classes  that Matt who runs the Farm has suggested to be led by Farm community. (see below)

His vision:  when ever you go to the Wellness Zone, there will be something that enhances your connection to your body or enriches your knowledge.

WELLNESS SESSIONS -- ALways something cool happening in Wellness Zone
--Nature & Body & Interpersonal

**Permaculture Class** --Cassie & Jared--Gardens/Green house

- Get in field, plant a tree
- Zone design
-learn while you plant

**Renewable Energy** (Decentralized) -- Joshua Tree (Super systems)-- Trailer
Maker kits
Solar kits

**Regenerative Agriculture** -- Cassie & Jared (fields)
**Mushroom Inoculation workshop** (Stephanie)

- Mushroom Grow kits
-inoculate logs with Shitake and Porcini
-learn about mushroom lore and mushroom biology


**Native Seed & Plant Walk** (Part 1)-- Meet at Greenhouse -- Cassie/Brian
**Fermentation Workshop** (Part 2) -- Greenhouse -- Cassie/Brian

- Fermenting vegetables for probiotics

**Trust & Transparency in Relationships** Morgan
**Bee Keeping & Honey making** -- Cassie & Kristin (plus Honey)

**MORNING TIME:**

- Breathwork-- Rabia (Dome or Tea Lounge or beach)
- Chi Gong -- Nadeem/ or Young

**UNSTRUCTURED TIME:**

- Beach walk -
- Ranch Tours -- 4 wheel drive vehicles
- Mountain Biking
- Steam bath
- Hike
- Juggling/stilt-walking/slack line (Brady)
- Creek Walk -- Bill
- Nap
- Art Table and Materials
- Listening Project
- Human Library


**NITE TIME: LIVE JAM:**

- Music Experimentation -- in Atrium-- looping pedals (lives in Mush House) --Aaron
- Performance: Dirtwire (tree)
- DJ -- Cooler (late night) or Medicine Wheel (1 hour at sunset)
- Puppet Parade -- Toni Tone [Need materials]
- Dinner music -- live performance
- Tea Lounge -- canned music at night; Ariel DJ to create a vibe
- Music Jam -- Brian/Richard -- Dome or fire
- Music Band-- resident band (Drifter) perform at dinner; Wandering Ohm
- Pour tea -- 10 PM - 2 AM in tea loung
- Improv Comedy -- John McCabe
- Ceremonial Release -- Fire circle 
- Cacao Ceremony -- pure cacao opening -- Matt S.
- Star gazing Night hike; myths & stories -- Joanna/Ben 
- Silent Disco
-
